#!/usr/bin/env python

"""Usage:
    findus sum [options] ([-] | <json>)
    findus reduce [options] ([-] | <json>)

Options:
  -h --help            show this help message and exit
  -v --verbose         print status messages
  -d --debug           print debug messages
  -V --version         print version

"""

import sys

from docopt import docopt
import logging

logger = logging.getLogger('cli')
formatter = logging.Formatter(fmt='[%(levelname)s][%(name)s] %(message)s')
handler = logging.StreamHandler()
handler.setFormatter(formatter)
logger.addHandler(handler)

from libfindus.ledger import Ledger

VERSION = '0.1'

def main(options):
    if options['--verbose']:
        logger.setLevel(logging.INFO)
    if options['--debug']:
        logger.setLevel(logging.DEBUG)
    if options['-']:
        ledger = Ledger(sys.stdin)
    else:
        ledger = Ledger(open(options['<json>']))
    if options['sum']:
        ledger.summary()
    if options['reduce']:
        ledger.summary()
        ledger.reduce()
        ledger.summary()

if __name__ == '__main__':
    # parse options based on docstring above
    options = docopt(__doc__, version='findus '+VERSION)
    main(options)
